export default
{

    "status": "SUCCESS",
    "statusCode": 200,
    "message": "Transaction successful!",
    "desc": "SUCCESS",
    "debug": null,
    "exception": null,
    "data": [
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "2999",
                            "defaultTransferPrice": "1999",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon, Aha, Eros now, Hotstar, Zee5, PiSHOW, AAO NXT",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1692343777514,
            "defaultTransferPrice": 0.0,
            "id": "64df1de1b050d47132147118",
            "packageName": "ONS02",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305f7f2e3f4c76586270305",
                    "providerName": "Eros now",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@erosnow.com",
                    "providerPhone": "8284748394",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/erosnow.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "63067a1ce3f4c7658627031c",
                    "providerName": "Hotstar",
                    "providerTier": "2",
                    "concurrentViews": 9,
                    "offeredPrice": 1,
                    "enduserPrice": 3,
                    "providerStatus": "0",
                    "integrationType": "1",
                    "stagingKey": "fh",
                    "productionKey": "y",
                    "providerEmail": "fs@gmail.com",
                    "providerPhone": "7845623586",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/hotstar.webp",
                    "deleteFlag": 0,
                    "validFrom": 1661731200000,
                    "validTo": 1661817600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e2126d7149b83d47785c68",
                    "providerName": "Zee5",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@zee5.com",
                    "providerPhone": "1800978933",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/zee5.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "635cf8ea4d0b360305eaed1e",
                    "providerName": "PiSHOW",
                    "providerTier": "1",
                    "concurrentViews": 5,
                    "offeredPrice": 5,
                    "enduserPrice": 4,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "abcd",
                    "productionKey": "abcd",
                    "providerEmail": "abc@gmail.com",
                    "providerPhone": "+916789567897",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/Pi+Show.png",
                    "deleteFlag": 0,
                    "validFrom": 1666224000000,
                    "validTo": 1696032000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                },
                {
                    "id": "63931f9a09c4a519c50fb0fb",
                    "providerName": "AAO NXT",
                    "providerTier": "2",
                    "concurrentViews": 3,
                    "offeredPrice": 70,
                    "enduserPrice": 90,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "abc@xyz.com",
                    "providerPhone": "9876543210",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/aoonxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1670544000000,
                    "validTo": 1702080000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "1000",
                            "defaultTransferPrice": "1",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "AAO NXT, Sun NXT, Hungama, Shemaroo Me, Epicon",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1692344231860,
            "defaultTransferPrice": 0.0,
            "id": "64df1fa7b050d4713214714b",
            "packageName": "ONS03",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "63931f9a09c4a519c50fb0fb",
                    "providerName": "AAO NXT",
                    "providerTier": "2",
                    "concurrentViews": 3,
                    "offeredPrice": 70,
                    "enduserPrice": 90,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "abc@xyz.com",
                    "providerPhone": "9876543210",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/aoonxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1670544000000,
                    "validTo": 1702080000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                },
                {
                    "id": "6305c596bf448c47a0a814a1",
                    "providerName": "Sun NXT",
                    "providerTier": "1",
                    "concurrentViews": 1,
                    "offeredPrice": 1000,
                    "enduserPrice": 1000,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "pkey",
                    "productionKey": "skey",
                    "providerEmail": "sun@sunnxt.com",
                    "providerPhone": "9834756439",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/sunnxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659225600000,
                    "validTo": 1660780800000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305bb6dbf448c47a0a8149f",
                    "providerName": "Shemaroo Me",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 1000,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "axjcbka",
                    "productionKey": "sdbcaj",
                    "providerEmail": "ram@Shemaroo.com",
                    "providerPhone": "8008009009",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/shemaroo.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659916800000,
                    "validTo": 1660953600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "0",
                            "defaultTransferPrice": "0",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1692610426779,
            "defaultTransferPrice": 0.0,
            "id": "64e32f7ab050d471321478e1",
            "packageName": "AdminPack",
            "franchiseFlag": 0,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "1000",
                            "defaultTransferPrice": "999",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "ETV WIN, Aha, Zee5, Epicon",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1692701037709,
            "defaultTransferPrice": 0.0,
            "id": "64e4916d86d377008b423ca8",
            "packageName": "ONS10",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "646b320601a74503dc0d5588",
                    "providerName": "ETV WIN",
                    "providerTier": "1",
                    "concurrentViews": 1,
                    "offeredPrice": 365,
                    "enduserPrice": 365,
                    "providerStatus": "1",
                    "integrationType": "3",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "contact@etvwin.com",
                    "providerPhone": "8008020555",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/etvwin.webp",
                    "deleteFlag": 0,
                    "validFrom": 1684713600000,
                    "validTo": 1716336000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1684738652701,
                    "updatedDate": null
                },
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e2126d7149b83d47785c68",
                    "providerName": "Zee5",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@zee5.com",
                    "providerPhone": "1800978933",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/zee5.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "0",
                            "defaultTransferPrice": "0",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Aha",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1694155276323,
            "defaultTransferPrice": 0.0,
            "id": "64fac20c0e06ff379d0a6f96",
            "packageName": "aha",
            "franchiseFlag": 0,
            "providersInfo": [
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "0",
                            "defaultTransferPrice": "0",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Zee5",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1694412535523,
            "defaultTransferPrice": 0.0,
            "id": "64feaef757c8777222fbcf53",
            "packageName": "admin3mzee5",
            "franchiseFlag": 0,
            "providersInfo": [
                {
                    "id": "62e2126d7149b83d47785c68",
                    "providerName": "Zee5",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@zee5.com",
                    "providerPhone": "1800978933",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/zee5.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "1000",
                            "defaultTransferPrice": "500",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Hungama, AAO NXT",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1696326648560,
            "defaultTransferPrice": 0.0,
            "id": "651be3f97913d77148fb96c0",
            "packageName": "testOnnet",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "63931f9a09c4a519c50fb0fb",
                    "providerName": "AAO NXT",
                    "providerTier": "2",
                    "concurrentViews": 3,
                    "offeredPrice": 70,
                    "enduserPrice": 90,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "abc@xyz.com",
                    "providerPhone": "9876543210",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/aoonxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1670544000000,
                    "validTo": 1702080000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "12 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "1000",
                            "defaultTransferPrice": "799",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon, Sony Liv, Hungama",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1697546138039,
            "defaultTransferPrice": 0.0,
            "id": "652e7f9a60e4d006d7f21472",
            "packageName": "MMohanPack",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e213b07149b83d47785c69",
                    "providerName": "Sony Liv",
                    "providerTier": "2",
                    "concurrentViews": 232,
                    "offeredPrice": 2234,
                    "enduserPrice": 2478,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "s",
                    "productionKey": "d",
                    "providerEmail": "s@sonyliv.com",
                    "providerPhone": "3672628299",
                    "apiDocumentPath": "/ottaggr/uploads/popularMedia.pdf",
                    "logoPath": "/ottaggr/uploads/sonyliv.webp",
                    "deleteFlag": 0,
                    "validFrom": 1657497600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "499",
                            "defaultTransferPrice": "299",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon, Aha, Hungama, Shemaroo Me, Sun NXT, Eros now, Zee5, PiSHOW, AAO NXT, ETV WIN",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1701669780041,
            "defaultTransferPrice": 0.0,
            "id": "656d6b943b34f82729514d3c",
            "packageName": "NewTest",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305bb6dbf448c47a0a8149f",
                    "providerName": "Shemaroo Me",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 1000,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "axjcbka",
                    "productionKey": "sdbcaj",
                    "providerEmail": "ram@Shemaroo.com",
                    "providerPhone": "8008009009",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/shemaroo.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659916800000,
                    "validTo": 1660953600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305c596bf448c47a0a814a1",
                    "providerName": "Sun NXT",
                    "providerTier": "1",
                    "concurrentViews": 1,
                    "offeredPrice": 1000,
                    "enduserPrice": 1000,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "pkey",
                    "productionKey": "skey",
                    "providerEmail": "sun@sunnxt.com",
                    "providerPhone": "9834756439",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/sunnxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659225600000,
                    "validTo": 1660780800000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305f7f2e3f4c76586270305",
                    "providerName": "Eros now",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@erosnow.com",
                    "providerPhone": "8284748394",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/erosnow.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e2126d7149b83d47785c68",
                    "providerName": "Zee5",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@zee5.com",
                    "providerPhone": "1800978933",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/zee5.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "635cf8ea4d0b360305eaed1e",
                    "providerName": "PiSHOW",
                    "providerTier": "1",
                    "concurrentViews": 5,
                    "offeredPrice": 5,
                    "enduserPrice": 4,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "abcd",
                    "productionKey": "abcd",
                    "providerEmail": "abc@gmail.com",
                    "providerPhone": "+916789567897",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/Pi+Show.png",
                    "deleteFlag": 0,
                    "validFrom": 1666224000000,
                    "validTo": 1696032000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                },
                {
                    "id": "63931f9a09c4a519c50fb0fb",
                    "providerName": "AAO NXT",
                    "providerTier": "2",
                    "concurrentViews": 3,
                    "offeredPrice": 70,
                    "enduserPrice": 90,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "abc@xyz.com",
                    "providerPhone": "9876543210",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/aoonxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1670544000000,
                    "validTo": 1702080000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                },
                {
                    "id": "646b320601a74503dc0d5588",
                    "providerName": "ETV WIN",
                    "providerTier": "1",
                    "concurrentViews": 1,
                    "offeredPrice": 365,
                    "enduserPrice": 365,
                    "providerStatus": "1",
                    "integrationType": "3",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "contact@etvwin.com",
                    "providerPhone": "8008020555",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/etvwin.webp",
                    "deleteFlag": 0,
                    "validFrom": 1684713600000,
                    "validTo": 1716336000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1684738652701,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "12 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "2000",
                            "defaultTransferPrice": "500",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon, Aha, Sony Liv, Hungama, Shemaroo Me, Sun NXT, Eros now",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1707488914414,
            "defaultTransferPrice": 0.0,
            "id": "65c636928d77003b132690e6",
            "packageName": "todayPack",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e213b07149b83d47785c69",
                    "providerName": "Sony Liv",
                    "providerTier": "2",
                    "concurrentViews": 232,
                    "offeredPrice": 2234,
                    "enduserPrice": 2478,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "s",
                    "productionKey": "d",
                    "providerEmail": "s@sonyliv.com",
                    "providerPhone": "3672628299",
                    "apiDocumentPath": "/ottaggr/uploads/popularMedia.pdf",
                    "logoPath": "/ottaggr/uploads/sonyliv.webp",
                    "deleteFlag": 0,
                    "validFrom": 1657497600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305bb6dbf448c47a0a8149f",
                    "providerName": "Shemaroo Me",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 1000,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "axjcbka",
                    "productionKey": "sdbcaj",
                    "providerEmail": "ram@Shemaroo.com",
                    "providerPhone": "8008009009",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/shemaroo.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659916800000,
                    "validTo": 1660953600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305c596bf448c47a0a814a1",
                    "providerName": "Sun NXT",
                    "providerTier": "1",
                    "concurrentViews": 1,
                    "offeredPrice": 1000,
                    "enduserPrice": 1000,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "pkey",
                    "productionKey": "skey",
                    "providerEmail": "sun@sunnxt.com",
                    "providerPhone": "9834756439",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/sunnxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659225600000,
                    "validTo": 1660780800000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305f7f2e3f4c76586270305",
                    "providerName": "Eros now",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@erosnow.com",
                    "providerPhone": "8284748394",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/erosnow.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "0",
                            "defaultTransferPrice": "0",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Aha, Hungama, Shemaroo Me",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1707731433111,
            "defaultTransferPrice": 0.0,
            "id": "65c9e9e932f9625cb1fb840a",
            "packageName": "adminPack1",
            "franchiseFlag": 0,
            "providersInfo": [
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305bb6dbf448c47a0a8149f",
                    "providerName": "Shemaroo Me",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 1000,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "axjcbka",
                    "productionKey": "sdbcaj",
                    "providerEmail": "ram@Shemaroo.com",
                    "providerPhone": "8008009009",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/shemaroo.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659916800000,
                    "validTo": 1660953600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "0",
                            "defaultTransferPrice": "0",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Hungama",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1707815289580,
            "defaultTransferPrice": 0.0,
            "id": "65cb3179848ce61a226a2cfc",
            "packageName": "admin",
            "franchiseFlag": 0,
            "providersInfo": [
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "1300",
                            "defaultTransferPrice": "200",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Hungama, Zee5, AAO NXT",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1707815655654,
            "defaultTransferPrice": 0.0,
            "id": "65cb32e789ba7f2caab623e3",
            "packageName": "tuesdayPack",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e2126d7149b83d47785c68",
                    "providerName": "Zee5",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@zee5.com",
                    "providerPhone": "1800978933",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/zee5.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "63931f9a09c4a519c50fb0fb",
                    "providerName": "AAO NXT",
                    "providerTier": "2",
                    "concurrentViews": 3,
                    "offeredPrice": 70,
                    "enduserPrice": 90,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "abc@xyz.com",
                    "providerPhone": "9876543210",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/aoonxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1670544000000,
                    "validTo": 1702080000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "300",
                            "defaultTransferPrice": "250",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon, Eros now, PiSHOW",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1672391600003,
            "defaultTransferPrice": 0.0,
            "id": "6393278666f9554bd4ab513e",
            "packageName": "PIOTB5",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305f7f2e3f4c76586270305",
                    "providerName": "Eros now",
                    "providerTier": "1",
                    "concurrentViews": 100,
                    "offeredPrice": 100,
                    "enduserPrice": 1,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "asa",
                    "productionKey": "wada",
                    "providerEmail": "ab@erosnow.com",
                    "providerPhone": "8284748394",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/erosnow.webp",
                    "deleteFlag": 0,
                    "validFrom": 1660608000000,
                    "validTo": 1661990400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "635cf8ea4d0b360305eaed1e",
                    "providerName": "PiSHOW",
                    "providerTier": "1",
                    "concurrentViews": 5,
                    "offeredPrice": 5,
                    "enduserPrice": 4,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "abcd",
                    "productionKey": "abcd",
                    "providerEmail": "abc@gmail.com",
                    "providerPhone": "+916789567897",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/Pi+Show.png",
                    "deleteFlag": 0,
                    "validFrom": 1666224000000,
                    "validTo": 1696032000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "100",
                            "defaultTransferPrice": "50",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Hungama, Shemaroo Me, Sun NXT",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1707827989658,
            "defaultTransferPrice": 0.0,
            "id": "65cb631550e92656f2b97ae9",
            "packageName": "mytest",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305bb6dbf448c47a0a8149f",
                    "providerName": "Shemaroo Me",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 1000,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "axjcbka",
                    "productionKey": "sdbcaj",
                    "providerEmail": "ram@Shemaroo.com",
                    "providerPhone": "8008009009",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/shemaroo.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659916800000,
                    "validTo": 1660953600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305c596bf448c47a0a814a1",
                    "providerName": "Sun NXT",
                    "providerTier": "1",
                    "concurrentViews": 1,
                    "offeredPrice": 1000,
                    "enduserPrice": 1000,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "pkey",
                    "productionKey": "skey",
                    "providerEmail": "sun@sunnxt.com",
                    "providerPhone": "9834756439",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/sunnxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659225600000,
                    "validTo": 1660780800000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "1000",
                            "defaultTransferPrice": "500",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon, Hungama, Shemaroo Me, AAO NXT, Sun NXT",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1707920621686,
            "defaultTransferPrice": 0.0,
            "id": "65cccced5130e53f5c324f88",
            "packageName": "lastTest",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305bb6dbf448c47a0a8149f",
                    "providerName": "Shemaroo Me",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 1000,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "axjcbka",
                    "productionKey": "sdbcaj",
                    "providerEmail": "ram@Shemaroo.com",
                    "providerPhone": "8008009009",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/shemaroo.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659916800000,
                    "validTo": 1660953600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "63931f9a09c4a519c50fb0fb",
                    "providerName": "AAO NXT",
                    "providerTier": "2",
                    "concurrentViews": 3,
                    "offeredPrice": 70,
                    "enduserPrice": 90,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "",
                    "productionKey": "",
                    "providerEmail": "abc@xyz.com",
                    "providerPhone": "9876543210",
                    "apiDocumentPath": "",
                    "logoPath": "/ottaggr/uploads/aoonxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1670544000000,
                    "validTo": 1702080000000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": null,
                    "updatedDate": null
                },
                {
                    "id": "6305c596bf448c47a0a814a1",
                    "providerName": "Sun NXT",
                    "providerTier": "1",
                    "concurrentViews": 1,
                    "offeredPrice": 1000,
                    "enduserPrice": 1000,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "pkey",
                    "productionKey": "skey",
                    "providerEmail": "sun@sunnxt.com",
                    "providerPhone": "9834756439",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/sunnxt.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659225600000,
                    "validTo": 1660780800000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "0",
                            "defaultTransferPrice": "0",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Aha",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1708406697322,
            "defaultTransferPrice": 0.0,
            "id": "65d437a97b31f70e3061cca3",
            "packageName": "PackAdmin",
            "franchiseFlag": 0,
            "providersInfo": [
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        },
        {
            "calculatedPrice": 0.0,
            "updatedDate": null,
            "packageStatus": 1,
            "packageType": 1,
            "pricingInfo": [
                {
                    "duration": "3 months",
                    "screensInfo": [
                        {
                            "numberOfScreens": "2 screen",
                            "price": "100",
                            "defaultTransferPrice": "50",
                            "offeredPrice": null
                        }
                    ]
                }
            ],
            "providersList": "Epicon, Aha, Hungama, Shemaroo Me",
            "deleteFlag": 0,
            "sellingPrice": 0.0,
            "createdDate": 1708407767551,
            "defaultTransferPrice": 0.0,
            "id": "65d43bd77b31f70e3061cccd",
            "packageName": "allPack1",
            "franchiseFlag": 1,
            "providersInfo": [
                {
                    "id": "62df85fed0fca969b3688f01",
                    "providerName": "Epicon",
                    "providerTier": "2",
                    "concurrentViews": 12,
                    "offeredPrice": 103,
                    "enduserPrice": 23,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "key1",
                    "productionKey": "key2",
                    "providerEmail": "epicon@epicon.net",
                    "providerPhone": "7589768967",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/epicon.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656806400000,
                    "validTo": 1658793600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e211537149b83d47785c67",
                    "providerName": "Aha",
                    "providerTier": "1",
                    "concurrentViews": 156,
                    "offeredPrice": 178,
                    "enduserPrice": 200,
                    "providerStatus": "1",
                    "integrationType": "2",
                    "stagingKey": "Abcd",
                    "productionKey": "Abcd",
                    "providerEmail": "arjun@aha.com",
                    "providerPhone": "1800899789",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/aha.webp",
                    "deleteFlag": 0,
                    "validFrom": 1658966400000,
                    "validTo": 1661558400000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "62e214987149b83d47785c6a",
                    "providerName": "Hungama",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 100,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "a",
                    "productionKey": "p",
                    "providerEmail": "hung@hungama.com",
                    "providerPhone": "7899567899",
                    "apiDocumentPath": "/ottaggr/uploads/videoImpressions.pdf",
                    "logoPath": "/ottaggr/uploads/hungama.webp",
                    "deleteFlag": 0,
                    "validFrom": 1656633600000,
                    "validTo": 1659225600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                },
                {
                    "id": "6305bb6dbf448c47a0a8149f",
                    "providerName": "Shemaroo Me",
                    "providerTier": "1",
                    "concurrentViews": 1000,
                    "offeredPrice": 1000,
                    "enduserPrice": 100,
                    "providerStatus": "1",
                    "integrationType": "1",
                    "stagingKey": "axjcbka",
                    "productionKey": "sdbcaj",
                    "providerEmail": "ram@Shemaroo.com",
                    "providerPhone": "8008009009",
                    "apiDocumentPath": "/ottaggr/uploads/PDF Test Page.pdf",
                    "logoPath": "/ottaggr/uploads/shemaroo.webp",
                    "deleteFlag": 0,
                    "validFrom": 1659916800000,
                    "validTo": 1660953600000,
                    "endpoints": {},
                    "optionalData": {},
                    "createdDate": 1663052620760,
                    "updatedDate": null
                }
            ]
        }
    ]
}